name: FastAPI Test Workflow

# Define em quais eventos o workflow será executado
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Usa uma máquina Ubuntu para rodar os testes

    steps:
      # Baixa o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configura o ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Ou qualquer versão de Python que você esteja usando

      # Instala as dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Rodando os testes com pytest
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()  # Somente se os testes passarem

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy FastAPI App
        run: |
          # Coloque aqui o comando para o deploy da sua aplicação
          echo "Fazendo o deploy da aplicação..."
